### ISSUE TITLE
Add TLS Support

### ISSUE THREAD

**Issue by griffobeid** [security-union/rust-zoom#18]
Currently you have to go to chrome://flags to get the app to work by allowing the insecure origin to bypass the security check. We could get the app to work on other browsers that have WebCodecs API like Firefox and not have to customize the browser if the server and frontend supported a TLS certificate

**Comment by darioalessandro** [comment]
I agree!!!

**Comment by darioalessandro** [comment]
I think that we can add tls certs to the nginx proxy || k8s ingress controller just like at May
