### ISSUE TITLE
Please rename your project

### ISSUE THREAD

**Issue by gdf8gdn8** [security-union/rust-zoom#4]
I've already mentioned: Yes they [zoom] will. They[zoom] are from land of "freedom" where suing people is common.
Besides that - zoom is a registered trademark in this context.

**Comment by anborg** [comment]
>They[zoom] are from land of "freedom" where suing people is common. Besides that - zoom is a registered trademark in this context.

Yes. Please rename.  But my reason is different.  Zoom as a company, bows down to certain authoritative govt and have a history of making data available to those authoritative govt.  Please clean up the project name. :-)

**Comment by anborg** [comment]
https://www.secureworld.io/industry-news/zoom-traffic-through-china-data-routing-controls

https://theintercept.com/2020/04/03/zooms-encryption-is-not-suited-for-secrets-and-has-surprising-links-to-china-researchers-discover/

https://www.forbes.com/sites/thomasbrewster/2020/04/03/warning-zoom-sends-encryption-keys-to-china-sometimes/?sh=ea2d4973fd94

**Comment by darioalessandro** [comment]
Hey @gdf8gdn8 @anborg : 

Thank you for stopping by and giving some feedback!

Let me be clear, if we ever create a commercial tele-conferencing system we will use an original name.

The awesome Rust community provided great feedback and I feel that we can pick one of those names (provided that the US allows us to register it). 

The purpose of naming this project rust-zoom was purely an seo + common sense decision. 

Zoom is used as a verb around the world and we wanted to deliberately piggy back on that.

I'll update the readme to clearly state this.

Let me know if this makes sense 😄

**Comment by darioalessandro** [comment]
How about: 
![undefined - Imgur](https://user-images.githubusercontent.com/1176339/198057386-22b88c88-b430-4cb3-a6fc-65eb38167195.png)
