### ISSUE TITLE
How do we get the delay between two meetingers?

### ISSUE THREAD

**Issue by lidh15** [security-union/rust-zoom#5]
Do we have this api in the project?

**Comment by darioalessandro** [comment]
Hi @lidh15 !! thank you for stopping by!

I intend to rewrite the transport using quic + webtransport as opposed to websockets.

Quic constantly compute rtt between the peers at all times.

If this does not work, I'll add some timestamps to the protobuf messages, if the computers have their clocks synced using srtp, it will be easy to compute the delay.

**Comment by lidh15** [comment]
I'm looking forward to it~

**Comment by darioalessandro** [comment]
Seems like https://github.com/hyperium/h3 is very close to supporting what we need for WebTransport!!
