### ISSUE TITLE
Resolution on screenshots is 2 high

### ISSUE THREAD

**Issue by bquast** [security-union/rust-zoom#9]
See title

**Comment by darioalessandro** [comment]
Hey @bquast, happy to help, which screenshots?

**Comment by bquast** [comment]
Hi @darioalessandro, I meant the resolution of the monitors that took the two screenshots in README.md are too high, making the content too small.

If you just lower the resolution while taking the screenshots, then the content will be larger in the image.

Does that make sense?

**Comment by darioalessandro** [comment]
yes

**Comment by darioalessandro** [comment]
This is done
